// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportProject(arg1) {
  window['go']['main']['Bridge']['ExportProject'](arg1);
}

export function ImportProject() {
  return window['go']['main']['Bridge']['ImportProject']();
}

export function LoadImage() {
  return window['go']['main']['Bridge']['LoadImage']();
}
