// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportProject(arg1:string):void;

export function ImportProject():Promise<string>;

export function LoadImage():Promise<string>;
